hostname: Router-1
interfaces:
  - name: GigabitEthernet0/0
    ip_address: 192.168.1.1
    subnet_mask: 255.255.255.0
    description: LAN Interface
  - name: GigabitEthernet0/1
    ip_address: 203.0.113.1
    subnet_mask: 255.255.255.0
    description: WAN Interface